import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {Home, Newspaper, Upload, MessageCircle, UserRound, Search, Bell, Heart, Share2, Download, MoreVertical, Send, Image as ImageIcon, Video, LogIn, LogOut, Settings, HelpCircle, Globe, Lock, Phone, Mail, Palette, X, CheckCircle2} from 'lucide-react';
import './styles.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;

const demoVideos = [
 {id:'demo-1',title:'U Rwanda rwacu 🇷🇼',creator:'Waxtix',views:'25.4K',duration:60,thumb:'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1000&q=80'},
 {id:'demo-2',title:'Ubuzima bwiza n’udushya',creator:'Waxtix Creator',views:'12.8K',duration:58,thumb:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80'},
 {id:'demo-3',title:'Uturere tw’u Rwanda',creator:'RwandaVibes',views:'8.6K',duration:47,thumb:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'},
 {id:'demo-4',title:'Imyitozo ya Fitness',creator:'SportLife',views:'15.2K',duration:60,thumb:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80'}
];

function App(){
 const [page,setPage]=useState('home'); const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [videos,setVideos]=useState([]); const [news,setNews]=useState([]); const [query,setQuery]=useState(''); const [menu,setMenu]=useState(false); const [theme,setTheme]=useState(localStorage.getItem('waxtix-theme')||'dark'); const [lang,setLang]=useState(localStorage.getItem('waxtix-lang')||'en');
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('waxtix-theme',theme)},[theme]);
 useEffect(()=>{localStorage.setItem('waxtix-lang',lang)},[lang]);
 useEffect(()=>{let active=true; if(!supabase)return; supabase.auth.getSession().then(({data})=>{if(active)setSession(data.session)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>{active=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!supabase||!session?.user)return; loadProfile(); loadContent()},[session]);
 async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle(); setProfile(data)}
 async function loadContent(){const [{data:v},{data:n}]=await Promise.all([supabase.from('videos').select('*,profiles(username,avatar_url)').order('created_at',{ascending:false}),supabase.from('news').select('*,profiles(username,avatar_url)').order('created_at',{ascending:false})]); setVideos(v||[]);setNews(n||[])}
 const filtered=useMemo(()=>[...demoVideos,...videos].filter(v=>(v.title||'').toLowerCase().includes(query.toLowerCase())),[query,videos]);
 const t=(en,rw)=>lang==='rw'?rw:en;
 return <div className="app"><header><div className="brand" onClick={()=>setPage('home')}><span className="logo">▶</span><b>Waxtix</b></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search videos, users, topics...','Shakisha video, abantu, insanganyamatsiko...')}/></div><button className="iconbtn"><Bell size={20}/></button></header>
 <main>{page==='home'&&<HomePage t={t} videos={filtered} session={session}/>} {page==='news'&&<NewsPage t={t} news={news}/>} {page==='upload'&&<UploadPage t={t} session={session} onDone={loadContent}/>} {page==='chat'&&<ChatPage t={t} session={session}/>} {page==='profile'&&<ProfilePage t={t} session={session} profile={profile} onProfile={setProfile}/>} {page==='auth'&&<AuthPage t={t}/>}</main>
 <nav><NavItem active={page==='home'} icon={<Home/>} label={t('Home','Home')} onClick={()=>setPage('home')}/><NavItem active={page==='news'} icon={<Newspaper/>} label={t('News','News')} onClick={()=>setPage('news')}/><NavItem active={page==='upload'} icon={<Upload/>} label={t('Upload','Upload')} onClick={()=>setPage(session?'upload':'auth')}/><NavItem active={page==='chat'} icon={<MessageCircle/>} label={t('Chat','Chat')} onClick={()=>setPage(session?'chat':'auth')}/><NavItem active={page==='profile'} icon={<UserRound/>} label={t('Profile','Profile')} onClick={()=>setPage(session?'profile':'auth')}/></nav>
 {menu&&<SideMenu t={t} session={session} onClose={()=>setMenu(false)} setPage={setPage} theme={theme} setTheme={setTheme} lang={lang} setLang={setLang}/>}<button className="floating-menu" onClick={()=>setMenu(true)}>☰</button></div>
}
function NavItem({active,icon,label,onClick}){return <button className={active?'navitem active':'navitem'} onClick={onClick}>{icon}<span>{label}</span></button>}
function HomePage({t,videos,session}){return <section className="page"><div className="hero"><span className="pill">🔥 {t('Trending','Birakunzwe')}</span><img src={videos[0]?.thumb||demoVideos[0].thumb}/><div className="heroText"><h1>{videos[0]?.title||demoVideos[0].title}</h1><small>{videos[0]?.views||demoVideos[0].views} views · 0:60</small></div><div className="play">▶</div></div><div className="actions"><button><Heart/> 1.2K</button><button><Share2/> {t('Share','Sangira')}</button><button><MessageCircle/> 342</button><button><Download/> {t('Download','Kuramo')}</button></div><div className="tabs"><b>{t('For You','Kuri wowe')}</b><span>{t('Following','Abo ukurikira')}</span></div><div className="grid">{videos.map(v=><VideoCard key={v.id} v={v} t={t}/>)}</div>{!session&&<div className="notice">{t('You can watch videos and read news without signing in. Sign in when you want to post, chat or use your profile.','Ushobora kureba video no gusoma amakuru utarinjiye. Injira ushaka kohereza, kuganira cyangwa gukoresha profile.')}</div>}</section>}
function VideoCard({v,t}){return <article className="card"><div className="thumb"><img src={v.thumb}/><span>{v.duration||60}s</span></div><h3>{v.title}</h3><small>{v.views||0} views · {v.creator||v.profiles?.username||'Creator'}</small><div className="mini-actions"><button><Heart size={16}/></button><button><Share2 size={16}/></button><button><Download size={16}/></button></div></article>}
function NewsPage({t,news}){return <section className="page"><div className="sectionTitle"><div><h2>News</h2><p>{t('News and photos','Amakuru n’amafoto')}</p></div><button className="primary"><Upload size={17}/> Add</button></div><div className="newsgrid">{news.map(n=><article className="news"><img src={n.image_url}/><div><h3>{n.title}</h3><p>{n.body}</p><small>{n.profiles?.username||'Waxtix'}</small></div></article>)}{news.length===0&&<div className="empty">📰 {t('No news yet. Add news from the Supabase dashboard or extend the upload form.','Nta makuru arahari. Ongeraho amakuru muri Supabase cyangwa wagure upload form.')}</div>}</div></section>}
function UploadPage({t,session,onDone}){const [kind,setKind]=useState('video');const [file,setFile]=useState(null);const [title,setTitle]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState(''); async function upload(){if(!supabase||!session)return setMsg('Supabase is not configured or you are not signed in.'); if(!file)return setMsg('Choose a file first.'); if(kind==='video'&&file.type.startsWith('video/')===false)return setMsg('Please choose a video.'); if(kind==='video'&&file.size>100*1024*1024)return setMsg('Video must be 100MB or smaller.'); setBusy(true);setMsg('');const ext=file.name.split('.').pop();const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const bucket=kind==='video'?'videos':'news-media';const {error:e}=await supabase.storage.from(bucket).upload(path,file,{upsert:false});if(e){setBusy(false);return setMsg(e.message)}const {data:pub}=supabase.storage.from(bucket).getPublicUrl(path);let error;if(kind==='video'){({error}=await supabase.from('videos').insert({user_id:session.user.id,title:title||'Untitled video',video_url:pub.publicUrl,duration:60}))}else{({error}=await supabase.from('news').insert({user_id:session.user.id,title:title||'Untitled news',body:'',image_url:pub.publicUrl}))}setBusy(false);setMsg(error?error.message:t('Uploaded successfully.','Byoherejwe neza.'));if(!error){setFile(null);setTitle('');onDone?.()}}
 return <section className="page narrow"><h2>{t('Upload','Upload')}</h2><div className="switch"><button className={kind==='video'?'selected':''} onClick={()=>setKind('video')}><Video/> Video</button><button className={kind==='news'?'selected':''} onClick={()=>setKind('news')}><ImageIcon/> News photo</button></div><label>{t('Title','Umutwe')}<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title"/></label><label>{kind==='video'?'Video file':'Photo file'}<input type="file" accept={kind==='video'?'video/*':'image/*'} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p className="hint">{t('Video upload is for videos only. You can choose sound in your video before uploading.','Upload ya video yakira video gusa. Ushobora guhitamo amajwi muri video mbere yo kuyohereza.')}</p><button className="primary wide" disabled={busy} onClick={upload}>{busy?'Uploading...':t('Upload now','Ohereza ubu')}</button>{msg&&<p className="status">{msg}</p>}</section>}
function ChatPage({t,session}){return <section className="page narrow"><h2>Chat 💬</h2><div className="chatbox"><div className="bubble">{t('Follow people to chat with them and make friends.','Kurikirana abantu ushaka kuganira nabo no gushaka inshuti.')}</div><div className="bubble muted">{t('Status can be added here.','Aha ushobora gushyiraho Status.')}</div></div><div className="chatInput"><input placeholder={t('Write a message...','Andika ubutumwa...')}/><button className="primary"><Send/></button></div></section>}
function ProfilePage({t,session,profile,onProfile}){const [username,setUsername]=useState(profile?.username||session?.user?.email?.split('@')[0]||'');const [saving,setSaving]=useState(false);async function save(){if(!supabase)return;setSaving(true);const {data}=await supabase.from('profiles').upsert({id:session.user.id,username,updated_at:new Date().toISOString()}).select().single();onProfile(data);setSaving(false)}return <section className="page narrow"><div className="profileHead"><div className="avatar">{username?.[0]?.toUpperCase()||'W'}</div><div><h2>{username||'Waxtix user'}</h2><small>{session.user.email||session.user.phone||''}</small></div></div><div className="stats"><div><b>0</b><span>Followers</span></div><div><b>0</b><span>Following</span></div><div><b>0</b><span>Views</span></div></div><label>Edit profile<input value={username} onChange={e=>setUsername(e.target.value)}/></label><button className="primary wide" onClick={save} disabled={saving}>{saving?'Saving...':'Save profile'}</button></section>}
function AuthPage({t}){const [mode,setMode]=useState('email');const [value,setValue]=useState('');const [code,setCode]=useState('');const [sent,setSent]=useState(false);const [msg,setMsg]=useState('');async function send(){if(!supabase)return setMsg('Add your Supabase environment variables first.');const opts={options:{shouldCreateUser:true}};const result=mode==='phone'?await supabase.auth.signInWithOtp({phone:value,...opts}):await supabase.auth.signInWithOtp({email:value,...opts});if(result.error)setMsg(result.error.message);else{setSent(true);setMsg('Code sent.')}}async function verify(){const result=mode==='phone'?await supabase.auth.verifyOtp({phone:value,token:code,type:'sms'}):await supabase.auth.verifyOtp({email:value,token:code,type:'email'});if(result.error)setMsg(result.error.message);else setMsg('Signed in.')}async function google(){if(!supabase)return;const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error)setMsg(error.message)}return <section className="page auth"><div className="authbox"><div className="brand big"><span className="logo">▶</span><b>Waxtix</b></div><h2>{t('Sign in','Injira')}</h2><div className="switch"><button className={mode==='email'?'selected':''} onClick={()=>{setMode('email');setSent(false)}}><Mail/> Email</button><button className={mode==='phone'?'selected':''} onClick={()=>{setMode('phone');setSent(false)}}><Phone/> Phone</button></div>{!sent?<><input value={value} onChange={e=>setValue(e.target.value)} placeholder={mode==='phone'?'+250...':'you@example.com'}/><button className="primary wide" onClick={send}>Send code</button></>:<><input value={code} onChange={e=>setCode(e.target.value)} placeholder="6-digit code" inputMode="numeric"/><button className="primary wide" onClick={verify}>Verify code</button></>}<button className="google" onClick={google}>G Continue with Google</button>{msg&&<p className="status">{msg}</p>}<small>{t('You may watch videos and read news without signing in.','Ushobora kureba video no gusoma amakuru utarinjiye.')}</small></div></section>}
function SideMenu({t,session,onClose,setPage,theme,setTheme,lang,setLang}){async function signout(){await supabase?.auth.signOut();onClose();setPage('home')}return <div className="overlay" onClick={onClose}><aside onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><h2>Menu</h2><button><Globe/> Change language<select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="rw">Kinyarwanda</option></select></button><button><HelpCircle/> Help Center</button><button><Settings/> My account</button><div className="sub"><span><Lock/> Password</span><span><Mail/> Email</span><span><Phone/> Phone number</span><span><Palette/> Theme colour</span></div><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Palette/> {theme==='dark'?'Light theme':'Dark theme'}</button>{session?<button className="danger" onClick={signout}><LogOut/> Sign out</button>:<button className="primary wide" onClick={()=>{onClose();setPage('auth')}}><LogIn/> Sign in</button>}</aside></div>}

createRoot(document.getElementById('root')).render(<App/>);
